kibot:
  version: 1

global:
  environment:
    symbols: ${KICAD8_SYMBOL_DIR}
    footprints: ${KICAD8_FOOTPRINT_DIR}
    models_3d: ${KICAD8_3DMODEL_DIR}
    templates: ${KICAD8_TEMPLATE_DIR}
    user_templates: ${KICAD8_USER_DIR}/template
    # extra_os:
    #   - KICAD_LIBS_DIR: ${KICAD_LIBS_DIR}

preflight:
  drc: true
  erc: true
  fill_zones: true
  draw_fancy_stackup: true
  update_pcb_characteristics: true

outputs:

  ## Plots Outputs ##

  - name: "gerber"
    comment: "Gerber files for PCB manufacturing."
    type: gerber
    dir: +plots/gerber
    options:
      # generic layer options
      exclude_edge_layer: false
      exclude_pads_from_silkscreen: false
      plot_sheet_reference: true
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      line_width: 0.15

      # gerber options
      use_aux_axis_as_origin: false
      subtract_mask_from_silk: true
      use_protel_extensions: false
      gerber_precision: 4.5
      create_gerber_job_file: true
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: false
    layers:
      - "copper"
      - "F.Mask"
      - "B.Mask"
      - "F.SilkS"
      - "B.SilkS"
      - "F.Fab"
      - "B.Fab"
      - "Edge.Cuts"
      - "User.Drawings"
      - "User.Comments"
  
  - name: "drill_with_map_pdf"
    comment: "Drill files for PCB manufacturing."
    type: excellon
    dir: +plots/drill
    options:
      # excellon options
      pth_and_npth_single_file: True
      map: "pdf"

  - name: "drill_map_dxf"
    comment: "Drill files for PCB manufacturing."
    type: excellon
    dir: +plots/drill
    options:
      # excellon options
      pth_and_npth_single_file: True
      map: "dxf"

  ## Fab Outputs ##

  - name: "schematic_pdf_annotated"
    comment: "Annotated PDF of the schematic."
    type: pdf_sch_print
    dir: +fab
    options:
      output: "%f-%i%I%v-annotated.%x"

  - name: "interactive_html_bom"
    comment: "Interactive HTML BOM."
    type: ibom
    dir: +fab
    options:
      include_tracks: true
      include_nets: true
      output: "%f-%i%I%v.%x" # %i=ibom
      blacklist_empty_val: true
      dark_mode: true
      highlight_pin1: true

  - name: "export_3d"
    comment: "3D model in STEP format."
    type: export_3d
    dir: +fab

  - name: "positions"
    comment: "Pick and place file."
    type: position
    dir: +fab
    options:
      format: ASCII
      only_smd: false

  - name: "positions-openpnp"
    comment: "Pick and place file with mirrored bottom components for OpenPNP."
    type: position
    dir: +openpnp
    options:
      format: ASCII
      only_smd: false
      include_virtual: true
      bottom_negative_x: true
  
  - name: "netlist_d356"
    comment: "Netlist in IPC-D-356 format."
    type: netlist
    dir: +fab
    options:
      format: "ipc"

  # - name: "diff"
  #   comment: "Diff file."
  #   type: diff
  #   dir: +fab

  ## BOM Outputs ##

  - name: "bom_csv"
    comment: "Bill of Materials in CSV format."
    type: bom
    dir: +bom
    options:
      csv:
        hide_pcb_info: true
        quote_all: true
      group_fields: [ "Manufacturer", "MPN" ]

      columns:
        - field: "References"
          name: "Reference"
        - field: "Value"
        - field: "Footprint"
        - field: "Datasheet"
        - field: "Quantity Per PCB"
          name: "Qty"
        - field: "Footprint Populate"
          name: "Populate"
        - field: "Standard Cost"
        - field: "Manufacturer"
        - field: "MPN"
        - field: "LCSC PN"
        - field: "Note"
  
  
