kibot:
  version: 1

preflight:
  erc: false
  drc: false

outputs:

  ## Fabrication Outputs ##

  - name: "gerber"
    comment: "Gerber files for PCB manufacturing."
    type: gerber
    dir: +manufacturing/fab/gerber
    options:
      # generic layer options
      exclude_edge_layer: false
      exclude_pads_from_silkscreen: false
      plot_sheet_reference: true
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      line_width: 0.15

      # gerber options
      use_aux_axis_as_origin: false
      subtract_mask_from_silk: true
      use_protel_extensions: false
      gerber_precision: 4.5
      create_gerber_job_file: true
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: false
      output: "${PCBA_PN}-${PCBA_REV}_%f_panel-%i%I%v.%x"
    layers:
      - copper
      - F.Mask
      - B.Mask
      - F.SilkS
      - B.SilkS
      - F.Fab
      - B.Fab
      - F.Paste
      - B.Paste
      - Edge.Cuts
      - User.Drawings
      - User.Comments
  
  - name: "drill_with_map_pdf"
    comment: "Drill files for PCB manufacturing."
    type: excellon
    dir: +manufacturing/fab/drill
    options:
      # excellon options
      pth_and_npth_single_file: True
      map: "pdf"
      output: "${PCBA_PN}-${PCBA_REV}_%f_panel-%i%I%v.%x"

  - name: "drill_map_dxf"
    comment: "Drill files for PCB manufacturing."
    type: excellon
    dir: +manufacturing/fab/drill
    options:
      # excellon options
      pth_and_npth_single_file: True
      map: "dxf"
      output: "${PCBA_PN}-${PCBA_REV}_%f_panel-%i%I%v.%x"

  - name: "netlist_d356"
    comment: "Netlist in IPC-D-356 format."
    type: netlist
    dir: +manufacturing/fab
    options:
      format: "ipc"
      output: "${PCBA_PN}-${PCBA_REV}_%f_panel-%i%I%v.%x"

  ## Assembly Outputs ##

  - name: "interactive_html_bom"
    comment: "Interactive HTML BOM."
    type: ibom
    dir: +manufacturing/assembly
    options:
      include_tracks: true
      include_nets: true
      output: "%f-%i%I%v.%x" # %i=ibom
      blacklist_empty_val: true
      dark_mode: true
      highlight_pin1: true
      output: "${PCBA_PN}-${PCBA_REV}_%f_panel-%i%I%v.%x"

  - name: "positions"
    comment: "Pick and place file."
    type: position
    dir: +manufacturing/assembly/pnp
    options:
      format: ASCII
      only_smd: false
      output: "${PCBA_PN}-${PCBA_REV}_%f_panel-%i%I%v.%x"

  ## Specialized Outputs ##

  - name: "positions-openpnp"
    comment: "Pick and place file with mirrored bottom components for OpenPNP."
    type: position
    dir: +special/openpnp
    options:
      format: ASCII
      only_smd: false
      include_virtual: true
      bottom_negative_x: true
      output: "${PCBA_PN}-${PCBA_REV}_%f_panel-%i%I%v.%x"

  ## Compress Outputs ##
  - name: "zip_manufacturing"
    comment: "ZIP manufacturing outputs."
    type: compress
    dir: manufacturing
    options:
      files:
        - source: 'manufacturing/**'
      output: ${PCBA_PN}-${PCBA_REV}_%f-manufacturing.%x
  
  - name: "zip_release"
    comment: "ZIP all files for release."
    type: compress
    options:
      files:
        - source: '**'
      output: ${PCBA_PN}-${PCBA_REV}_%f.%x